#!/bin/bash
y='\033[1;93m'
c="\033[0;36m"
g="\e[92;1m"
r="\033[1;31m"
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
bc="\e[5;36m"
ungu='\033[0;35m'
Green_background="\033[42;37m"
Red_background="\033[41;37m"
Suffix="\033[0m"
NC='\e[0m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
White="\033[97;1m"
Green="\033[92;1m"
Cyan="\033[96;1m"
Xark='\e[0m'
BG_BLU="\033[44;1m" # BG BIRU
clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
On_IPurple='\033[0;105m'  #
On_IRed='\033[0;101m'
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
NC='\e[0m'
nama=$(cat /etc/xray/username)
clear
function xdxl_Banner() {
clear
baris_panjang
echo -e "\033[95;1m     $nama       \033[0m"
baris_panjang
}

function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}

function  FIXX() {
  echo -e  " ${BG_BLU}               MENU FIXX              ${Xark}"
}

function  ADMIN() {
  echo -e  " ${BG_BLU}               ADMIN AKSES              ${Xark}"
}

function  CLEAR() {
  echo -e  " ${BG_BLU}               MENU CLEAR             ${Xark}"
}


function  INFORMATION() {
  echo -e  " ${BG_BLU}              INFORMATION             ${Xark}"
}


function  OTHER() {
  echo -e  " ${BG_BLU}                OTHER                 ${Xark}"
}


function Create_Bot_Notif() {
  create-bot-notif
}


function Info_Port() {
  prot
}

# Banner 
function Banner(){
clear
baris_panjang
ATAS
baris_panjang
}

r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
echo -e ""
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y System OS ${NC}     $Blue=$NC $MODEL${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y Server RAM ${NC}    $Blue=$NC $RAM MB $NC"
echo -e " ${z}│$NC$r ⇲ $NC$y Uptime Server ${NC} $Blue=$NC $SERONLINE${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y Date ${NC}          $Blue=$NC $DATEVPS${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y Time ${NC}          $Blue=$NC $TIMEZONE${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y IP VPS ${NC}        $Blue=$NC $IPVPS${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y Domain ${NC}        $Blue=$NC $domain${NC}"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC\033[41m                       MENU SETTING                       $NC${z}│$NC"
echo -e " ${z}├══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}│$NC [${r}01${NC}]$purple Running Service    "  
echo -e " ${z}│$NC [${r}02${NC}]$purple Restart Service    " 
echo -e " ${z}│$NC [${r}03${NC}]$purple Auto Reboot	  " 
echo -e " ${z}│$NC [${r}04${NC}]$purple Monitoring         " 
echo -e " ${z}│$NC [${r}05${NC}]$purple SpeedTest 		  "
echo -e " ${z}│$NC [${r}06${NC}]$purple Delete All Account Exp "
echo -e " ${z}│$NC [${r}07${NC}]$purple Factory Reset      "
echo -e " ${z}│$NC [${r}08${NC}]$purple Install SlowDns    "  
echo -e " ${z}│$NC [${r}09${NC}]$purple Change Banner      "  
echo -e " ${z}│$NC [${r}10${NC}]$purple Change Domain      "  
echo -e " ${z}│$NC [${r}11${NC}]$purple Fixx Haproxy       "  
echo -e " ${z}│$NC [${r}12${NC}]$purple Fixx Domain        "  
echo -e " ${z}│$NC [${r}13${NC}]$purple Fix Akun Pada Bot  "  
echo -e " ${z}│$NC [${r}14${NC}]$purple Clear Cache      "
echo -e " ${z}│$NC [${r}15${NC}]$purple Clear Logs       "
echo -e " ${z}│$NC [${r}16${NC}]$purple Clear Cache File "
echo -e " ${z}│$NC [${r}17${NC}]$purple Info Service Port  "
echo -e " ${z}│$NC [${r}18${NC}]$purple Information System "
echo -e " ${z}│$NC [${r}19${NC}]$purple Limit-on-off XRAY  "
echo -e " ${z}│$NC [${r}20${NC}]$purple Back to Menu"
echo -e " ${z}│$NC [${r}00${NC}]$purple EXIT "
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC\033[41m                   CONTACT SUPPORT / CS                   $NC${z}│$NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${z}╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y Telegram ${NC}     $Blue=$NC @FranataaSTORE${NC}"
echo -e " ${z}│$NC$r ⇲ $NC$y WhatsApp ${NC}     $Blue=$NC 6282241967317 $NC"
echo -e " ${z}╰══════════════════════════════════════════════════════════╯${NC}"
echo -e ""
echo -e ""
read -p "Select From Options :  " NB
case $NB in
1) clear ; run ;;
2) clear ; reset ;;
3) clear ; autoreboot ;;
4) clear ; gotop ;;
5) clear ; speedtest ;;
6) clear ; xp ;;
7) clear ; Factreset ;;
8) clear ; wget -q https://nata.serv00.net/v1.8/Fls/nameserver && chmod +x nameserver && ./nameserver && reset ;;
9) clear ; nano /etc/banner.txt ;;
10) clear ; change-domain ;;
11) clear ; fixhap ;;
12) clear ; fixcert ;;
13) clear ; fixakunbot ;;
14) clear ; clearcache ;;
15) clear ; clearlog ;;
16) clear ; delet-cache-file ;;
17) clear ; Info_Port ;;
18) clear ; about ;;
19) clear ; limit-on-off ;;
20) clear ; menu ;;
x) exit ;;
*) m-ftr ;;
esac
}


Banner
Menu_Lambofgod
Select_Menu